# Site settings
title: getaccountant.github.io/eric
email: ericsmith.accountant@yahoo.com
author: Eric Smith
description: "Eric Smith - Quickbooks Bookkeeping"
baseurl: "/eric"
url: "oldtownaccountant.github.io"
twitter_username: eric_accountant
github_username:  getaccountant
linkedin_username: ericrsmith
facebook_username: eric.accountant

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-60569533-1'

gems:
  - jekyll-sitemap
