# Site settings
title: grumaccountant.github.io/eric
email: ericsmith.accountant@yahoo.com
author: Eric Smith
description: "Eric Smith - Quickbooks Bookkeeping"
baseurl: "/eric"
url: "grumacountant.github.io/eric"
twitter_username: eric_accountant
github_username:  grumaccountant
linkedin_username: ericrsmith
facebook_username: eric.accountant

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-60569533-1'

gems:
  - jekyll-sitemap
